version: "3"
services:
  web:
    image: springboot-docker-poc
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 200M
      restart_policy:
        condition: on_failure
    ports:
      - "9090:8080"
    networks:
      - webnet
networks:
  webnet:
